### ISSUE TITLE
Line 290 in the source file tpm2-luks-unlock.sh

### ISSUE THREAD

**Issue by jensaymoo** [kelderek/TPM2-LUKS#11]
Hello.

Why are you storing the keys unencrypted inside the `/usr/local/sbin/tpm2-getkey` file? Line 290 in the `tpm2-luks-unlock.sh` source file. Do I understand correctly that the file /usr/local/sbin/tpm2-getkey is copied into the initrd image, and in fact there is no benefit from TPM2? Maybe the `/usr/local/sbin/tpm2-getkey` script should have the line  `echo $(tpm2_nvread -s 64 0x1500016)` instead of `echo /*64 bytes key of passphase*/`?

**Comment by kelderek** [comment]
Yikes that was a boneheaded move on my part.  I never intended to store the actual key in tpm2-getkey, as you said that defeats the point of using the TPM2 at all.  Thanks for the great catch!  I merged your PR #12 in and will update the release tomorrow.  I am away from my test setup today and I need to make sure of the correct path forward to fixing this for existing users.  I am pretty sure they will just need to run the script again, either keeping the key or generating a new one if they prefer.
